changelog:
  categories:
    - title: "🚀 Features"
      labels: ["feat","feature"]
    - title: "🐛 Fixes"
      labels: ["fix","bug"]
    - title: "⚡ Performance"
      labels: ["perf"]
    - title: "♻️ Refactor"
      labels: ["refactor"]
    - title: "📝 Docs"
      labels: ["docs"]
    - title: "✅ Tests"
      labels: ["test"]
    - title: "🏗️ Build/CI/Chore"
      labels: ["build","ci","chore"]
    - title: "⏪ Revert"
      labels: ["revert"]
  exclude:
    labels: ["skip-changelog"]
  template: |
    ## Summary
    <!-- 간단 변경 요약(사람 친화) -->

    ## Changes
    

    ## Contributors
    