name: housekeeping

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0'  # 매주 월요일 03:00 KST

permissions:
  contents: write
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs (release.yml만)
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: 'release.yml'
          retain_days: 30
          keep_minimum_runs: 30
          delete_run_by_conclusion_pattern: '.*'   # 모든 상태 허용

      - name: Delete older releases (keep last 10, delete tags)
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}